name: well_path
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.6+1
environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.5
  pin_code_fields: ^7.4.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  http: ^0.13.4
  chopper: ^5.1.0
  chucker_flutter:
    git:
      url: https://github.com/syedmurtaza108/chucker-flutter.git
      ref: logger
  intl:
  image_picker: ^0.8.4+8
  injectable: ^1.5.3
  get_it: ^7.2.0
  shared_preferences: ^2.0.11
  i69n: ^2.1.0
  connectivity_plus: ^2.2.0
  mask_text_input_formatter: ^2.0.0
  cupertino_icons: ^1.0.2
  spider: ^4.2.0
  sms_otp_auto_verify: ^2.1.0
  bot_toast: ^4.0.1
  local_auth: ^2.1.6
  gauges: ^1.0.0
  fl_chart: ^0.62.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  flutter_draggable_gridview: ^0.0.8
  collection: ^1.17.1
  path_provider: ^2.0.15
  path: ^1.8.3
  open_file: ^3.3.2
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0
  screenshot: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.20.1
  build_runner: ^2.1.4
  freezed: ^2.1.1
  chopper_generator: ^5.1.0
  json_serializable: ^6.1.4
  injectable_generator: ^1.5.4
  flutter_lints: ^2.0.0
  flutter_gen_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 200
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 800