import 'package:well_path/gen/assets.gen.dart';

class HealthyLiving {
  final HealthyLivingContent healthyLivingContent;
  HealthyLiving({required this.healthyLivingContent});
}

class HealthyLivingContent {
  final String name;
  final String content;
  final String imagePath;
  final String bannerImagePath;

  HealthyLivingContent(
      {required this.name,
      required this.content,
      required this.imagePath,
      required this.bannerImagePath});
}

HealthyLivingContent healthyLivingContentDiet = HealthyLivingContent(
    name: "Diet",
    content: "Hypertension, or high blood pressure, is a prevalent health issue worldwide. Often referred to as the \"silent killer,\" it contributes to various health risks, including heart disease and stroke. Lifestyle changes, such as diet modification, can significantly aid in managing blood pressure levels. Among various dietary approaches, the DASH (Dietary Approaches to Stop Hypertension) diet has shown notable success in controlling hypertension and reducing Blood Pressure.\n\nThe DASH diet is a dietary pattern promoted by the National Heart, Lung, and Blood Institute (NHLBI) to prevent and control hypertension. It focuses on eating whole foods rich in nutrients that are essential for heart health. These include fruits, vegetables, whole grains, lean proteins, and low-fat dairy products, while limiting saturated fats, red meats, and sugars.\n\nThis eating plan is rich in dietary fiber, potassium, calcium, and magnesium—all vital nutrients that play a role in maintaining a healthy blood pressure. Dietary fiber helps reduce the body's absorption of cholesterol, thereby reducing the risk of heart disease. On the other hand, potassium helps the body get rid of sodium, which can help lower blood pressure levels. Calcium and magnesium contribute to relaxation of blood vessels, which supports healthy blood pressure.\n\nNotably, the DASH diet doesn't just focus on what you eat, but also on how much you eat. It encourages portion control, which aids in maintaining a healthy weight—a crucial aspect in blood pressure management. Remember, obesity increases the risk of hypertension.\n\nThe benefits of the DASH diet extend beyond blood pressure control. As a well-balanced, nutrient-dense diet, it also aids in weight management, improving gut health, and reducing the risk of other chronic diseases such as diabetes and certain types of cancer.\n\nAdopting the DASH diet doesn't require radical changes in your eating habits. Instead, it's about making gradual, sustainable adjustments. Start by adding an extra serving of vegetables to your meals, swapping refined grains with whole grains, and choosing lean proteins. Limit your intake of processed foods, which are often high in sodium and unhealthy fats.", 
    imagePath: Assets.images.healthyDiet.path,
    bannerImagePath: Assets.images.healthyDietBanner.path);

HealthyLivingContent healthyLivingContentExercise = HealthyLivingContent(
    name: "Exercise",
    content:"Exercise is a crucial aspect for maintaining heart health and reducing the risk of cardiovascular diseases. Needless to say there is a substantial body of research that demonstrates the beneficial effects of physical activity on cardiovascular health.\n\nYou should aim for at least 150 minutes of moderate-intensity aerobic activity or 75 minutes of vigorous aerobic activity per week, or a combination of both. Moderate-intensity activities include brisk walking, swimming, or  mowing the lawn. In contrast, vigorous activities involve running, jumping rope, and competitive sports. A good rule of thumb is that during moderate activities, you should be able to talk, but not sing, while during vigorous activities, you should be able to say only a few words without getting out of breath.\n\nWhen creating a workout plan, don't forget to incorporate muscle-strengthening activities. Engaging in moderate- to high-intensity muscle-strengthening activities, such as resistance or weight training, at least two days per week is strongly suggested. These activities should involve all major muscle groups, including legs, hips, back, abdomen, chest, shoulders, and arms.\n\nWhen possible, it is best to spread physical activity throughout the week rather than doing  it all in one or two days. This approach ensures that the heart is regularly stimulated, which can contribute to maintaining its health and strength.\n\nIt is also important to talk about those of us who live a sedentary lifestyle,   which has become increasingly common in the modern world.  The amount of time spent being sedentary, like sitting for long periods, can contribute to worse health. The hardest part will always be getting started and making that change to a more active lifestyle. Once started, the days become easier and healthier habits can be cultivated.\n\nIf you find it challenging to make the change to a more active and healthy lifestyle , start slow and gradually increase the duration and intensity of physical activity. Small steps, such as walking more and taking the stairs, can be powerful starting points.\n\nLastly, it's essential to choose physical activities that are enjoyable and suit individual fitness levels. This will not only make it easier to stick to the routine but also improve overall well-being.",
    imagePath: Assets.images.healthyExercise.path,
    bannerImagePath: Assets.images.healthyExerciseBanner.path);

HealthyLivingContent healthyLivingContentSleep = HealthyLivingContent(
    name: "Sleep",
    content: "Sleep plays an important role in various aspects of our lives, including memory consolidation, learning, creativity, emotional regulation, immune function, and overall health. It is not just a passive state, but an active process that is essential for our brain and body to function optimally.\n\nThere is an alarming prevalence of sleep disorders in modern society. Inadequate sleep negatively affects our cognitive abilities, mood, productivity, and long-term health, making us more susceptible to various chronic conditions such as obesity, diabetes, cardiovascular disease, and even cancer.\n\nThe following are suggestions which will likely help improve the quality of one’s sleep.\n\n1. Maintain a Consistent Sleep Schedule: Go to bed and awake at the same time every day, including the weekends. This promotes the regulation of the body’s internal clock and overall better sleep quality.\n\n2.	Make Your Environment Sleep-Friendly: Keep the bedroom cool, dark, and quiet. Blackout curtains, earplugs or white noise machines can block out external disturbances.\n\n3. Limit Exposure to Artificial Light: Avoid blue light especially at least one hour before bedtime. Use apps or setting which reduce blue light emission.\n\n4.	Practice a Relaxing Bedtime Routine: Engage in relaxing activities prior to sleep, ie read a book, warm bath, mindfulness or mediation, or calming music.\n\n5. Limit Stimulants and Depressants: Avoid stimulants such as caffeine, nicotine, and alcohol close to bedtime; caffeine at least 6 hours prior to sleep. Alcohol leads to worse sleep quality overall.\n\n6. Exercise Regularly: Regularly physical activity, preferably earlier in the day, can promote better sleep.\n\n7. Avoid Napping Late in the Day: Napping too close to bedtime or for long durations may interfere with nighttime sleep.\n\n8. Manage Stress and Anxiety: Stress reduction techniques may be used to help manage stress and improve sleep.\n\n 9. Consult a Healthcare Profession: A healthcare professional who specializes in sleep medicine may provide greater insight into what physical and emotional factors are affecting your sleep.",
    imagePath: Assets.images.healthySleep.path,
    bannerImagePath: Assets.images.healthySleepBanner.path);

HealthyLivingContent healthyLivingContentStress = HealthyLivingContent(
    name: "Stress",
    content:
        "Stress is the activation of various aspects of the nervous and hormone system of the body in response to physical and emotional stimuli.\n\nEmotional Symptoms of stress include:\n\n• Difficulty relaxing \n• Agitation, frustration \n• Feeling overwhelmed \n• Low self esteem \n\n Physical Symptoms of Stress Include:\n\n• Headaches \n• Fatigue \n• Upset stomach, nausea, diarrhea, constipation.\n• Aches, pains \n• Rapid heart rate, chest pain \n• Insomnia \n• Jaw clenching/grinding \n• Dry mouth \n\nThere are a multitude of different ways to combat stress once its effects are recognized. Relaxation techniques are available, including breathing exercises, meditation, yoga, progressive muscle relaxation. Regular exercise raises endorphins and helps relieve stress. General improvements in lifestyle habits also help diminish stress over time. We always recommend discussing with your Physician further recommendations for clinically and evidence-based stress reduction techniques, as well as for resources to local support groups. Follow the link below for further information. \n\n https://www.heart.org/en/healthy-living/healthy-lifestyle/stress-management ",
    imagePath: Assets.images.healthyStress.path,
    bannerImagePath: Assets.images.healthyStressBanner.path);

HealthyLivingContent healthyLivingContentSmoking = HealthyLivingContent(
    name: "Smoking",
    content:
        "Smoking is a highly addictive habit that poses significant risks to both the smoker and those exposed to secondhand smoke. The detrimental health effects of smoking are well-documented. Nicotine, a potent component in tobacco, constricts blood vessels and stimulates the release of adrenaline. This dual effect results in accelerated heart rates and elevated blood pressure. However, quitting smoking provides immediate health benefits to the smoker and continued benefits over the rest of their lifetime. There are a multitude of resources available for those interested in quitting smoking including the American Cancer Society’s Quitline (1-800-QUIT-NOW) and smokefree.gov, which offer free resources, information, and personalized quit plans. Seek counseling and behavioral support, when possible, with professional counselors and therapist, as well as medical professionals who will be able to provide medication replacement therapies to help manage withdrawal symptoms and cravings.\n\nHere are three effective tips to start your journey towards smoke-free living:\n\nSet a Quit Date: Having a specific day earmarked as your \"quit day\" makes the process more real and encourages commitment\n\nIdentify Triggers: Recognize situations that tempt you to smoke and develop strategies to avoid or handle them.\n\nSeek Support: Reach out to family, friends, or quitline services for motivation and guidance. Consult a healthcare provider for professional help; they can suggest nicotine replacement therapies or medications to manage cravings and withdrawal symptoms.\n\nRemember, it's never too late to quit smoking and regain control over your health.",
    imagePath: Assets.images.healthySmoking.path,
    bannerImagePath: Assets.images.healthySmokingBanner.path);

HealthyLivingContent healthyLivingContentAlcohol = HealthyLivingContent(
    name: "Alcohol",
    content:
        "Introduction:\n\nHigh blood pressure, also known as hypertension, is a common medical condition that affects a significant number of individuals worldwide. Lifestyle factors, such as diet and alcohol consumption, can influence blood pressure levels. In this article, we will explore the relationship between alcohol and its effects on high blood pressure.\n\nThe Link Between Alcohol and High Blood Pressure:\n\nResearch suggests that excessive alcohol consumption can contribute to high blood pressure. While moderate alcohol intake may have some cardiovascular benefits, excessive or chronic alcohol consumption can have detrimental effects on blood pressure regulation.\n\nImmediate Effects of Alcohol on Blood Pressure:\n\nWhen consumed, alcohol can cause a temporary increase in blood pressure. This is primarily due to its vasodilatory effects, meaning it relaxes and widens blood vessels. Consequently, blood flow increases, and blood pressure temporarily rises. However, the effects are typically short-lived, and blood pressure returns to normal as alcohol is metabolized.\n\nLong-term Effects of Alcohol on High Blood Pressure:\n\nExtended periods of heavy drinking can lead to sustained high blood pressure. Chronic alcohol consumption may damage the blood vessels and impair the function of the heart, contributing to hypertension. Excessive alcohol intake can also result in weight gain, which is another risk factor for high blood pressure.\n\nRecommendations for Alcohol Consumption:\n\nIf you have high blood pressure or are concerned about developing it, it is advisable to moderate your alcohol consumption or, in some cases, avoid it altogether. The guidelines for moderate alcohol intake vary by country and individual health status. However, generally, moderate drinking is defined as: \n\n• Up to one drink per day for women \n •	Up to two drinks per day for men \n\nIt is important to note that these guidelines refer to standard drink sizes, such as a 5-ounce (148 mL) glass of wine, 12 ounces (355 mL) of beer, or 1.5 ounces (44 mL) of distilled spirits.\n\nConclusion:\n\nWhile moderate alcohol consumption may have some cardiovascular benefits, excessive and chronic alcohol intake can contribute to high blood pressure. It is essential to be mindful of your alcohol consumption and adhere to recommended guidelines to maintain a healthy blood pressure level. If you have concerns about alcohol and its effects on your health, it is always best to consult with a healthcare professional who can provide personalized advice and guidance.",
    imagePath: Assets.images.healthyAlcohol.path,
    bannerImagePath: Assets.images.healthyAlcoholBanner.path);

HealthyLivingContent healthyLivingContentIntegrativeMedicine = HealthyLivingContent(
    name: "Integrative Medicine",
    content:
        "High blood pressure, or hypertension, is a prevalent health condition that affects many individuals globally. Alongside conventional medical approaches, integrative medicine offers a holistic approach to health and well-being. In this article, we will explore the concept of integrative medicine and its potential effects on high blood pressure management.\n\nUnderstanding Integrative Medicine:\n\nIntegrative medicine is an approach that combines conventional medical practices with evidence-based complementary therapies and lifestyle interventions. It emphasizes treating the whole person—mind, body, and spirit—and focuses on personalized care to address the root causes of health conditions.\n\nIntegrative Medicine and High Blood Pressure Management:\n\n When it comes to high blood pressure management, integrative medicine can play a supportive role. It recognizes that multiple factors contribute to hypertension, including lifestyle choices, stress, nutrition, physical activity, and emotional well-being. Integrative medicine aims to address these factors comprehensively to improve overall health and blood pressure control.\n\nComplementary Therapies in Integrative Medicine:\n\nSeveral complementary therapies can potentially assist in managing high blood pressure when used in conjunction with conventional medical care. Some of these therapies include: \n\nMind-Body Practices:\n\nTechniques like meditation, deep breathing exercises, yoga, and tai chi can help reduce stress, promote relaxation, and support blood pressure control. \n\nHerbal and Nutritional Supplements:\n\nCertain supplements, such as garlic, hawthorn, and omega-3 fatty acids, have been studied for their potential benefits in blood pressure management. However, it is recommended to consult with a healthcare professional before using any supplements, as they may interact with medications or have other contraindications.\n\nAcupuncture:\n\nThis traditional Chinese medicine practice involves the insertion of thin needles into specific points on the body. Some studies suggest that acupuncture may help lower blood pressure, although further research is needed to establish its effectiveness. \n\nExercise and Physical Activity:\n\nRegular physical activity, tailored to an individual's needs and capabilities, can be beneficial for blood pressure management. Integrative medicine promotes incorporating exercise into one's lifestyle as part of a holistic approach. \n\nIntegrative medicine offers a comprehensive approach to high blood pressure management, addressing various aspects of an individual's well-being. Complementary therapies and lifestyle interventions, when used alongside conventional medical care, may potentially support blood pressure control and overall health. It is crucial to consult with healthcare professionals knowledgeable in integrative medicine to develop an individualized plan that considers one's specific health needs and goals.",
    imagePath: Assets.images.healthyIntegrativemedicine.path,
    bannerImagePath: Assets.images.healthyIntegrativemedicineBanner.path);

List<HealthyLiving> healthyLiving = [
  HealthyLiving(healthyLivingContent: healthyLivingContentDiet),
  HealthyLiving(healthyLivingContent: healthyLivingContentExercise),
  HealthyLiving(healthyLivingContent: healthyLivingContentSleep),
  HealthyLiving(healthyLivingContent: healthyLivingContentStress),
  HealthyLiving(healthyLivingContent: healthyLivingContentSmoking),
  HealthyLiving(healthyLivingContent: healthyLivingContentAlcohol),
  HealthyLiving(healthyLivingContent: healthyLivingContentIntegrativeMedicine),
];
